#!/usr/bin/env bash
# Test for Bug #4 fix (Lucy's Maddy report 2026-06-06): plain
# `bash scripts/sync-workspace.sh` silent-committed everything when the
# workspace had a stray `.git` but was never properly sync-initialized
# (no whitelist in `.git/info/exclude`, no `.sutando-vault/ws-id`).
# Fix: `_assert_sync_initialized` runs after the `.git` presence check
# inside _push_only_impl + _pull_only_impl, and dies with a clear
# "run --init first" error if neither sentinel is present.

set -u
# NOTE: deliberately not `set -e` — these tests accumulate failures via
# `fail=1` and report at the end; transient grep-no-match exits would
# kill the script before the assertion summary prints.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
SYNC="$REPO/scripts/sync-workspace.sh"

fail=0

# Test 1: structural — helper function is declared
grep -q "^_assert_sync_initialized()" "$SYNC" \
    || { echo "  FAIL: _assert_sync_initialized() function missing"; fail=1; }

# Test 2: structural — helper is called inside _push_only_impl
PUSH_BLOCK="$(awk '/^_push_only_impl\(\) \{/,/^}$/' "$SYNC")"
echo "$PUSH_BLOCK" | grep -q '_assert_sync_initialized "push-only"' \
    || { echo "  FAIL: _assert_sync_initialized not called inside _push_only_impl"; fail=1; }

# Test 3: structural — helper is called inside _pull_only_impl
PULL_BLOCK="$(awk '/^_pull_only_impl\(\) \{/,/^}$/' "$SYNC")"
echo "$PULL_BLOCK" | grep -q '_assert_sync_initialized "pull-only"' \
    || { echo "  FAIL: _assert_sync_initialized not called inside _pull_only_impl"; fail=1; }

# Test 4: structural — helper accepts SUTANDO_SYNC_SKIP_INIT_GUARD override
grep -q "SUTANDO_SYNC_SKIP_INIT_GUARD" "$SYNC" \
    || { echo "  FAIL: SUTANDO_SYNC_SKIP_INIT_GUARD override missing"; fail=1; }

# Test 5: structural — helper checks the .git/info/exclude marker
grep -q 'Generated by sync-workspace.sh' "$SYNC" \
    || { echo "  FAIL: whitelist marker grep missing from helper"; fail=1; }

# Test 6: structural — helper checks the .sutando-vault/ws-id sentinel
grep -q '.sutando-vault/ws-id' "$SYNC" \
    || { echo "  FAIL: .sutando-vault/ws-id sentinel check missing"; fail=1; }

# Test 7: structural — guard runs AFTER the .git presence check
# (otherwise the .git-absent case dies with the wrong message)
push_lines="$(echo "$PUSH_BLOCK" | grep -n 'is not a git repo\|_assert_sync_initialized' | head -2)"
git_line=$(echo "$push_lines" | grep 'is not a git repo' | cut -d: -f1)
init_line=$(echo "$push_lines" | grep '_assert_sync_initialized' | cut -d: -f1)
if [ -n "$git_line" ] && [ -n "$init_line" ] && [ "$git_line" -ge "$init_line" ]; then
    echo "  FAIL: _assert_sync_initialized appears BEFORE the .git presence check in _push_only_impl (push would die with wrong message when .git missing)"
    fail=1
fi

# ── Function-logic E2E (tests 8-11) — exercise the helper directly.
# Sourcing the script triggers the dispatcher + acquires the global
# /tmp/sync-workspace.lock.d lock (which would collide with any cron),
# so we extract the function body and define it in this shell. The
# structural tests above prove the wiring; these tests prove the LOGIC.
TMP_E2E="$(mktemp -d -t sutando-sync-uninit-e2e.XXXXXX)"

# Re-implement the helper inline. Mirror of scripts/sync-workspace.sh.
# Kept in lockstep with the script — if these diverge, structural tests
# 5+6 still catch missing marker/sentinel grep in the script.
_assert_sync_initialized() {
    local _caller="${1:-sync}"
    [ "${SUTANDO_SYNC_SKIP_INIT_GUARD:-0}" = "1" ] && return 0
    local _exclude="$WORKSPACE_DIR/.git/info/exclude"
    local _wsid="$WORKSPACE_DIR/.sutando-vault/ws-id"
    if [ -f "$_exclude" ] && grep -q "Generated by sync-workspace.sh" "$_exclude" 2>/dev/null; then
        return 0
    fi
    if [ -f "$_wsid" ]; then
        return 0
    fi
    echo "ERR: ${_caller}: $WORKSPACE_DIR has .git but sync was never initialized"
    return 1
}

# Test 8: uninit .git fails the guard
mkdir -p "$TMP_E2E/uninit/.git/info"
# .git/info/exclude is absent — uninit state
WORKSPACE_DIR="$TMP_E2E/uninit"
out8="$(_assert_sync_initialized "test" 2>&1)"
rc8=$?
if [ "$rc8" = "0" ]; then
    echo "  FAIL: T8 — uninit workspace passed the guard"; fail=1
fi
echo "$out8" | grep -q "never initialized" \
    || { echo "  FAIL: T8 — error message missing 'never initialized'"; fail=1; }

# Test 9: marker present → passes
mkdir -p "$TMP_E2E/with-marker/.git/info"
cat > "$TMP_E2E/with-marker/.git/info/exclude" << 'EOF'
# Generated by sync-workspace.sh — do not edit by hand.
*
EOF
WORKSPACE_DIR="$TMP_E2E/with-marker"
if ! _assert_sync_initialized "test" >/dev/null 2>&1; then
    echo "  FAIL: T9 — workspace with marker rejected by guard"; fail=1
fi

# Test 10: ws-id sentinel alone → passes
mkdir -p "$TMP_E2E/with-wsid/.sutando-vault"
echo "abc123" > "$TMP_E2E/with-wsid/.sutando-vault/ws-id"
WORKSPACE_DIR="$TMP_E2E/with-wsid"
if ! _assert_sync_initialized "test" >/dev/null 2>&1; then
    echo "  FAIL: T10 — workspace with ws-id rejected by guard"; fail=1
fi

# Test 11: override env-var bypasses the guard on uninit
WORKSPACE_DIR="$TMP_E2E/uninit"
SUTANDO_SYNC_SKIP_INIT_GUARD=1 _assert_sync_initialized "test" >/dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "  FAIL: T11 — SUTANDO_SYNC_SKIP_INIT_GUARD=1 did NOT bypass guard"; fail=1
fi

# Cleanup
rm -rf "$TMP_E2E"

# Report
if [ "$fail" = "0" ]; then
    echo "ALL TESTS PASS"
else
    echo "TESTS FAILED"
    exit 1
fi
